### ISSUE TITLE
Sett opp blogg på netlife.com

### ISSUE THREAD

**Issue by olemagnus** [netliferesearch/netlife2019#10]
- [x] Gjør ferdig schema
- [x] Sett opp sidemal
- [x] Flytt over data fra Medium
- [x] Ordne Canoncial-urls for det som er importert

**Comment by olemagnus** [comment]
Are driver å importerer

**Comment by dreamyguy** [comment]
Stenger denne, det som er listet er gjort. Vi tar videreutvikling på en annen sak.
