### ISSUE TITLE
Koble om netlife.com

### ISSUE THREAD

**Issue by olemagnus** [netliferesearch/netlife2019#20]
- [ ] Overfør netlife.com-domenet til Netlify
- [ ] Lag et subdomene til gamle netlife.com, som heter old.netlife.com
- [ ] Legg til noindex på sidene på old.netlife.com
- [ ] legg til 301 i _redirects

**Comment by tatsuminetlife** [comment]
Edit netlify form emails

**Comment by tatsuminetlife** [comment]
Går du igenom Oles checklista @torgeirbeyer ?
