### ISSUE TITLE
Create a page that lists out all blog posts

### ISSUE THREAD

**Issue by olemagnus** [netliferesearch/netlife2019#28]
Clone the events (kurs og konferanser) page and make it list out all the blog posts with the same style. 
This is enough for a MVP. We will redesign this page later, but the issue only covers the MVP.

**Comment by tatsuminetlife** [comment]
We wen't for the tjenester template approach here. 4 featured, 4 in grid and the rest as archive list.

**Comment by cindydeltufo** [comment]
Never wrote this but I think the ppl involved in illegally printing a book about my & my family did. The author already threatened me to keep my mouth closed when she saw my name
