### ISSUE TITLE
Adjust alignment of startpage content

### ISSUE THREAD

**Issue by Martegraberg** [netliferesearch/netlife2019#55]
![Skjermbilde 2019-11-06 kl. 16.45.03.png](https://images.zenhubusercontent.com/5db16b8c7fc7fd0001050576/4e66aee8-71db-4ddd-b395-255537369256)

**Comment by tatsuminetlife** [comment]
- [ ]  Increase margin between netlife and menu.
- [ ]  Increase negative margin on the animation
- [ ]  Make a larger svg
